export const SEARCH_ITEMS = [
  // Core sections
  { name: 'Home', path: '/' },
  { name: 'Hot Games', path: '/hot-games' },
  { name: 'Slots', path: '/slots-games' },
  { name: 'Fish Games', path: '/fish-games' },
  { name: 'Live Games', path: '/live-games' },
  { name: 'Sports Games', path: '/sports-games' },
  { name: 'E-Sports', path: '/esports' },
  { name: 'Favorites', path: '/favorites' },
  { name: 'Poker Games', path: '/poker-games' },
  { name: 'Lottery', path: '/lottery' },

  // Hot Games
  { name: 'Super Ace', path: '/' },
  { name: 'Boxing King', path: '/' },
  { name: 'Fortune Gems', path: '/' },
  { name: 'Money Coming', path: '/' },
  { name: 'Fortune Gems 3', path: '/' },
  { name: 'Super Ace Deluxe', path: '/' },
  { name: 'Safari King', path: '/' },
  { name: 'Lucky Jaguar', path: '/' },
  { name: 'Thai Hilo', path: '/' },
  { name: 'Shōgun', path: '/' },
  { name: 'Cricket Roulette', path: '/' },
  { name: 'Golden Bank 2', path: '/' },

  // Slots Games
  { name: 'Blackjack Classic', path: '/' },
  { name: 'Roulette European', path: '/' },
  { name: 'Baccarat Live', path: '/' },
  { name: 'Poker Texas Hold\'em', path: '/' },
  { name: 'Dragon Tiger', path: '/' },
  { name: 'Sic Bo Live', path: '/' },
  { name: 'Crazy Time', path: '/' },
  { name: 'Monopoly Live', path: '/' },
  { name: 'Lightning Roulette', path: '/' },
  { name: 'Dream Catcher', path: '/' },
  { name: 'Gonzo\'s Treasure Hunt', path: '/' },
  { name: 'Mega Ball', path: '/' },
  { name: 'Wheel of Fortune', path: '/' },
  { name: 'Deal or No Deal', path: '/' },
  { name: 'Crazy Coin Flip', path: '/' },
  { name: 'Cash or Crash', path: '/' },

  // Live Games
  { name: 'Lightning Blackjack', path: '/' },
  { name: 'Immersive Roulette', path: '/' },
  { name: 'Speed Baccarat', path: '/' },
  { name: 'Infinite Blackjack', path: '/' },
  { name: 'Auto Roulette', path: '/' },
  { name: 'VIP Blackjack', path: '/' },
  { name: 'Dragon Tiger Live', path: '/' },
  { name: 'Baccarat Squeeze', path: '/' },
  { name: 'Roulette Royale', path: '/' },
  { name: 'Blackjack Party', path: '/' },
  { name: 'Mega Ball Live', path: '/' },
  { name: 'Crazy Time Live', path: '/' },
  { name: 'Monopoly Live Show', path: '/' },
  { name: 'Dream Catcher Live', path: '/' },
  { name: 'Gonzo\'s Treasure Hunt Live', path: '/' },
  { name: 'Wheel of Fortune Live', path: '/' },

  // Fish Games
  { name: 'Crash Game', path: '/' },
  { name: 'Plinko', path: '/' },
  { name: 'Dice', path: '/' },
  { name: 'Mines', path: '/' },
  { name: 'Hilo', path: '/' },
  { name: 'Limbo', path: '/' },
  { name: 'Keno', path: '/' },
  { name: 'Wheel', path: '/' },
  { name: 'Blackjack', path: '/' },
  { name: 'Baccarat', path: '/' },
  { name: 'Roulette', path: '/' },
  { name: 'Poker', path: '/' },
  { name: 'Lottery', path: '/' },
  { name: 'Scratch Cards', path: '/' },
  { name: 'Virtual Sports', path: '/' },
  { name: 'Instant Win', path: '/' },

  // Jeetbuzz related
  { name: 'Jeetbuzz', path: '/jeetbuzz' },
  { name: 'Jeetbuzz Game', path: '/jeetbuzz-game' },
  { name: 'Jeetbuzz Login', path: '/jeetbuzz-login' },
  { name: 'Jeetbuzz Casino', path: '/jeetbuzz-casino' },
  { name: 'Jeetbuzz Online', path: '/jeetbuzz-online' },
  { name: 'Jeetbuzz Partner', path: '/jeetbuzz-partner' },

  // Crickex related
  { name: 'Crickex', path: '/crickex' },
  { name: 'Crickex Login', path: '/crickex-login' },
  { name: 'Crickex Bet', path: '/crickex-bet' },
  { name: 'Crickex App', path: '/crickex-app' },
  { name: 'Crickex Online', path: '/crickex-online' },
  { name: 'Crickex Account Create', path: '/crickex-account-create' },
  { name: 'Crickex Bonus', path: '/crickex-bonus' },
  { name: 'Crickex BD Login', path: '/crickex-bd-login' },
  { name: 'Crickex Betting App', path: '/crickex-betting-app' },
  { name: 'Crickex Bet Bangla', path: '/crickex-bet-bangla' },

  // Other brands
  { name: 'BGD33', path: '/bgd33' },
  { name: 'BETBDT', path: '/betbdt' },
  { name: 'TK999', path: '/tk999' },
  { name: 'CK444', path: '/ck444' },
  { name: 'L444 Online Game', path: '/l444' },
];

